### ISSUE TITLE
how do I build this project without errors?

### ISSUE THREAD

**Issue by oladipo** [rbkmoney/hellgate#547]
tried to build the project with make.

got the following error:

`~/rbkmoney/hellgate$ make
/usr/bin/rebar3 update
/usr/bin/rebar3 compile
===> Verifying dependencies...
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
Makefile:46: recipe for target 'compile' failed
make: *** [compile] Error 1`

ran rebar3 compile with DIAGNOSTICS see output:

`~/rbkmoney/hellgate$ DIAGNOSTIC=1 make
/usr/bin/rebar3 update
===> 23.2.3 satisfies the requirement for minimum OTP version 21
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> Expanded command sequence to be run: [update]
===> Running provider: update
===> Getting definition for package accept from repo hexpm (#{api_url => <<"https://hex.pm/api">>,name => <<"hexpm">>,
         repo_name => <<"hexpm">>,repo_organization => undefined,
         repo_url => <<"https://repo.hex.pm">>,repo_verify => true,
         repo_verify_origin => true})
===> Getting definition for package bear from repo hexpm
===> Getting definition for package cache from repo hexpm
===> Getting definition for package certifi from repo hexpm
===> Getting definition for package coveralls from repo hexpm
===> Getting definition for package cowboy from repo hexpm
===> Getting definition for package cowlib from repo hexpm
===> Getting definition for package erlfmt from repo hexpm
===> Getting definition for package gproc from repo hexpm
===> Getting definition for package hackney from repo hexpm
===> Getting definition for package idna from repo hexpm
===> Getting definition for package inaka_aleppo from repo hexpm
===> Getting definition for package jsx from repo hexpm
===> Getting definition for package katana_code from repo hexpm
===> Getting definition for package metrics from repo hexpm
===> Getting definition for package mimerl from repo hexpm
===> Getting definition for package parse_trans from repo hexpm
===> Getting definition for package prometheus from repo hexpm
===> Getting definition for package prometheus_cowboy from repo hexpm
===> Getting definition for package prometheus_httpd from repo hexpm
===> Getting definition for package ranch from repo hexpm
===> Getting definition for package rebar3_archive_plugin from repo hexpm
===> Getting definition for package rebar3_proper from repo hexpm
===> Getting definition for package ssl_verify_fun from repo hexpm
===> Getting definition for package unicode_util_compat from repo hexpm
===> Getting definition for package zipper from repo hexpm
/usr/bin/rebar3 compile
===> 23.2.3 satisfies the requirement for minimum OTP version 21
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> Expanded command sequence to be run: [app_discovery,install_deps,lock,compile]
===> Running provider: app_discovery
===> Found top-level apps: [hellgate,hg_client,hg_proto,party_management,pm_client,pm_proto]
	using config: [{src_dirs,["src"]},{lib_dirs,["apps/*","lib/*","."]}]
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/cache/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/gproc/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody/rebar.config.script"
===> Running provider: install_deps
===> Verifying dependencies...
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/plugins/coveralls/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/plugins/jsx/rebar.config.script"
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git --version

===> 	opts: []

===> Port Cmd: git --version
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/damsel"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/damsel"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 7a9d7a6 with 7a9d7a6
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_client"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_client"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 9e11f50 with 9e11f50
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody/rebar.config.script"
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/erl_health"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/erl_health"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 982af88 with 982af88
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib/rebar.config.script"
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 7087d8b with 7087d8b
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 4565a8d with 4565a8d
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/how_are_you"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/how_are_you"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 29f9d3d with 29f9d3d
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/folsom/rebar.config.script"
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/mg_proto"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/mg_proto"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref d814d69 with d814d69
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/party_client"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/party_client"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 113ed40 with 113ed40
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody/rebar.config.script"
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/payproc_errors"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/payproc_errors"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref ebbfa37 with ebbfa37
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Compile (apps)
===> Setting paths to [plugins]
===> Setting paths to [deps]
===> Setting paths to [plugins]
===> Setting paths to [plugins]
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/scoper"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/scoper"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 89a973b with 89a973b
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/shumpune_proto"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/shumpune_proto"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref a0aed3b with a0aed3b
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref f2cd308 with f2cd308
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/cache/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/gproc/rebar.config.script"
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody_user_identity"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody_user_identity"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref a480762 with a480762
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib/rebar.config.script"
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody/rebar.config.script"
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/cg_mon"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/cg_mon"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 5a87a37 with 5a87a37
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_core"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_core"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 5a0ff39 with 5a0ff39
===> Evaluating config script "/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib/rebar.config.script"
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/folsom"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/folsom"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref eeb1cc4 with eeb1cc4
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/snowflake"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/snowflake"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref de15948 with de15948
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git rev-parse --short=7 -q HEAD

===> 	opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/thrift"}]

===> Port Cmd: git rev-parse --short=7 -q HEAD
Port Opts: [{cd,"/home/oladipo/rbkmoney/hellgate/_build/default/lib/thrift"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Comparing git ref 846a081 with 846a081
===> Running provider: lock
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/thrift' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/thrift"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/thrift' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/snowflake' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/snowflake"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/snowflake' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/folsom' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/folsom"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/folsom' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_core' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_core"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_core' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/cg_mon' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/cg_mon"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/cg_mon' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody_user_identity' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/woody_user_identity"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody_user_identity' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/woody"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/woody' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/shumpune_proto' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/shumpune_proto"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/shumpune_proto' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/scoper' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/scoper"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/scoper' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/payproc_errors' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/payproc_errors"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/payproc_errors' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/party_client' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/party_client"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/party_client' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/mg_proto' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/mg_proto"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/mg_proto' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/how_are_you' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/how_are_you"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/how_are_you' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/genlib' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/erl_health' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/erl_health"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/erl_health' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_client' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_client"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/dmt_client' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/damsel' rev-parse --verify HEAD

===> 	opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /home/oladipo/rbkmoney/hellgate/_build/default/lib/damsel"}]

===> Port Cmd: git -C '/home/oladipo/rbkmoney/hellgate/_build/default/lib/damsel' rev-parse --verify HEAD
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Running provider: compile
===> Setting paths to [deps]
===> Compile (apps)
===> Running hooks for compile in app cowlib (/home/oladipo/rbkmoney/hellgate/_build/default/lib/cowlib) with configuration:
===> 	{pre_hooks, []}.
===> run_hooks("/home/oladipo/rbkmoney/hellgate/_build/default/lib/cowlib", pre_hooks, compile) -> no hooks defined

===> Running hooks for compile in app accept (/home/oladipo/rbkmoney/hellgate/_build/default/lib/accept) with configuration:
===> 	{pre_hooks, []}.
===> run_hooks("/home/oladipo/rbkmoney/hellgate/_build/default/lib/accept", pre_hooks, compile) -> no hooks defined

===> Running hooks for compile in app fault_detector_proto (/home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto) with configuration:
===> Setting paths to [plugins]
===> 	{provider_hooks, [{pre, [{thrift,compile}]}]}.
===> Running provider: {thrift,compile}
===> Thrift compiler opts: [{in_dir,"proto"},
                                   {in_files,all},
                                   {out_erl_dir,"src"},
                                   {out_hrl_dir,"include"},
                                   {gen,
                                       "erlang:app_prefix=fd_proto,scoped_typenames"}]
===> Thrift compiler input files: ["/home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto/proto/base.thrift",
                                          "/home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto/proto/fault_detector.thrift"]
===> sh info:
	cwd: "/home/oladipo/rbkmoney/hellgate"
	cmd: thrift -r --gen erlang:app_prefix=fd_proto,scoped_typenames --out /home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto/src /home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto/proto/base.thrift

===> 	opts: [return_on_error]

===> Port Cmd: thrift -r --gen erlang:app_prefix=fd_proto,scoped_typenames --out /home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto/src /home/oladipo/rbkmoney/hellgate/_build/default/lib/fault_detector_proto/proto/base.thrift
Port Opts: [exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof,binary]

===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badrecord,dict}
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
Makefile:46: recipe for target 'compile' failed
make: *** [compile] Error 1`

What could be the issue?

**Comment by ciiol** [comment]
It needs to have [`thrift` executable](https://github.com/rbkmoney/thrift) in your PATH to allow [rebar3_thrift_compiler](https://github.com/rbkmoney/rebar3_thrift_compiler) rebar3 plugin work. It's also possible to use our build image, which already contains thrift.

I added more details and command examples to README. I hope it will be helpful.

**Comment by oladipo** [comment]
Thanks @ciiol, I am unable to get your build images. I am not sure it's in a public repository. can you point me to where I can get them?

**Comment by oladipo** [comment]
Hey. sorry I just read the README. Will follow the instructions and see what happens.

**Comment by oladipo** [comment]
Yea. hellgate compiles fine now.
